### ISSUE TITLE
Block-diagonal XCA?

### ISSUE THREAD

**Issue by blakechi** [facebookresearch/xcit#11]
Hello,
It seems like the [XCA](https://github.com/facebookresearch/xcit/blob/master/xcit.py#L221) doesn't use separated parameters for each head and I can't find the implementation for the block-diagonal one. I'm curious about why the implementation doesn't include it? Sorry if my understanding is incorrect.

**Comment by aelnouby** [comment]
Thanks for your questions. The heads play the role of blocks in that context https://github.com/facebookresearch/xcit/blob/0e6589eef0ae3f325be53228d119fe97f7a92882/xcit.py#L239

Therefore, only features within a head (d_h) attend to each other. Therefore, the d \times d matrix is block diagonal with d_h \times d_h blocks. We kept the term heads instead of blocks to be consistent with other Gram based self-attention implementations and reduce confusion. Please do not hesitate if you have any more questions.
