### ISSUE TITLE
Can't read files from the datasets folder

### ISSUE THREAD

**Issue by RichardYann** [facebookresearch/xcit#18]
Thanks for your work!

I met a problem when I try to follow the steps in the readme.md

I try to set the datapath by:
`python main.py --data-path 'F:\Projects\AI\ImageNet'`
However, it comes:
`RuntimeError: Found 0 files in subfolders of: F:\Projects\AI\ImageNet\train`

I'm sure the path is right, and there are all .JPEG files in this train folder, but it seems can't read any of them.

**Comment by woctezuma** [comment]
Is what you call the "train folder" an actual **`train/` subfolder** of this `data-path`?
- https://github.com/pytorch/examples/issues/236

If so, could you create a `1/` subfolder so that you get a `train/1/` subfolder as in:
- https://github.com/pytorch/examples/issues/236#issuecomment-432697252

For reference, this is the default parameter:

https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/main.py#L144-L145

which is then parsed by `torchvision.datasets`:

https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/datasets.py#L10

https://github.com/facebookresearch/xcit/blob/82f5291f412604970c39a912586e008ec009cdca/datasets.py#L69-L70

**Comment by RichardYann** [comment]
It works！

Thanks a lot！
